#!usr/bin/env python
# coding:utf-8

__author__ = 'sunyaxiong'


class A(object):

    def __init__(self):
        print 'enter A'
        print 'leave A'

class B(A):

    def __init__(self):
        print 'enter B'
        super(B, self).__init__()
        print 'leave B'


if __name__ == '__main__':
    b = B()