# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-12 08:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20160729_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('born_time', models.DateTimeField(auto_created=True, default=datetime.datetime.now, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('instance_uuid', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='UUID')),
                ('list_name', models.CharField(max_length=255, null=True, verbose_name='\u6e05\u5355\u4e3b\u673a\u540d')),
                ('hostname', models.CharField(max_length=255, null=True, verbose_name='\u4e3b\u673a\u540d')),
                ('ip', models.GenericIPAddressField(null=True, verbose_name='IP\u5730\u5740')),
                ('template', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u662f\u5426\u6a21\u677f')),
                ('os', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u64cd\u4f5c\u7cfb\u7edf')),
                ('os_version', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u64cd\u4f5c\u7cfb\u7edf\u7248\u672c\u53f7')),
                ('total_hard_disk', models.IntegerField(blank=True, null=True, verbose_name='\u603b\u786c\u76d8\u5bb9\u91cf')),
                ('cpu', models.IntegerField(blank=True, null=True, verbose_name='CPU\u6838\u5fc3\u6570\u91cf')),
                ('mem', models.IntegerField(blank=True, null=True, verbose_name='\u5185\u5b58')),
                ('delivery_time', models.DateField(blank=True, max_length=20, null=True, verbose_name='\u8d44\u6e90\u4ea4\u4ed8\u65f6\u95f4')),
                ('delete_time', models.DateField(blank=True, max_length=20, null=True, verbose_name='\u8d44\u6e90\u5220\u9664\u65f6\u95f4')),
                ('tools_status', models.CharField(blank=True, max_length=20, null=True, verbose_name='tools\u72b6\u6001')),
                ('guest_status', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u72b6\u6001')),
                ('power_status', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u7535\u6e90\u72b6\u6001')),
                ('esxi_host', models.GenericIPAddressField(blank=True, null=True, verbose_name='esxi\u4e3b\u673aIP')),
                ('vc', models.GenericIPAddressField(blank=True, null=True, verbose_name='VCenterIP')),
                ('app_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5e94\u7528\u540d\u79f0')),
                ('app_role', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5e94\u7528\u89d2\u8272')),
                ('app_description', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5e94\u7528\u63cf\u8ff0')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='\u4e0a\u6b21\u4fee\u6539\u65f6\u95f4')),
            ],
            options={
                'verbose_name': 'Vsphere\u5e73\u53f0\u865a\u62df\u673a',
                'verbose_name_plural': 'Vsphere\u5e73\u53f0\u865a\u62df\u673a',
            },
        ),
    ]
