# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-12 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListInfoLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u6e05\u5355\u540d')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='ip')),
                ('col', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u53d8\u5316\u5b57\u6bb5')),
                ('val_from', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u66f4\u65b0\u524d')),
                ('val_to', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u66f4\u65b0\u540e')),
                ('flag', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u589e\u5220\u6807\u8bb0')),
                ('action_time', models.DateTimeField(blank=True, null=True, verbose_name='\u53d8\u66f4\u65f6\u95f4')),
                ('vm_ins', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.List', to_field='instance_uuid', verbose_name='vm\u5b9e\u4f8b')),
            ],
            options={
                'verbose_name': 'vm\u4fe1\u606f\u53d8\u52a8\u65e5\u5fd7\u5e93',
                'verbose_name_plural': 'vm\u4fe1\u606f\u53d8\u52a8\u65e5\u5fd7\u5e93',
            },
        ),
    ]
